name: Practice
api: ["3.0.0"]
version: "0.0.1"
main: practice\PracticeCore
description: Core for Venom
depend: ["FormAPI"]
permissions:
  practice.permission.kit:
    description: "Allows players to use the command /kit"
    default: true
  practice.permission.kit.create:
    description: "Allows players to use the command /kit create"
    default: op
  practice.permission.kit.delete:
    description: "Allows players to use the command /kit delete"
    default: op
  practice.permission.kit.name:
    description: "Allows players to use the /kit [kit-name] command."
    default: true
  practice.permission.kit.item:
    description: "Allows players to use the /kit item command."
    default: op
  practice.permission.kit.effect:
    description: "Allows players to use the /kit effect command."
    default: op
  practice.permission.arena:
    description: "Allows players to use the command /arena"
    default: true
  practice.permission.arena.create:
    description: "Allows players to use the commmand /arena create"
    default: op
  practice.permission.arena.delete:
    description: "Allows players to use the command /arena deslete"
    default: op
  practice.permission.arena.list:
    description: "Allows players to use the commmand /arena list"
    default: op
  practice.permission.arena.tp:
    description: "Allows players to use the command /arena tp"
    default: true
  practice.permission.arena.kit:
    description: "Allows players to use the command /arena kit"
    default: op
  practice.permission.arena.pos1:
    description: "Allows players to use the command /arena pos1"
    default: op
  practice.permission.arena.pos2:
    description: "Allows players to use the command /arena pos2"
    default: op
  practice.permission.freeze:
    description: "Allows player to use the freeze/unfreeze command"
    default: op
  practice.permission.spawn:
    description: "Allows player to use the /spawn command"
    default: true
  practice.permission.heal:
    description: "Allows player to use the /heal command"
    default: op
  practice.permission.feed:
    description: "Allows player to use the /feed command"
    default: op
  practice.permission.fly:
    description: "Allows player to use the /fly command"
    default: op
  practice.permission.report:
    description: "Allows player to use the /report command"
    default: true
  practice.permission.report.edit:
    description: "Allows player to use the /report edit command"
    default: op
  practice.permission.report.list:
    description: "Allows player to use the /report list command"
    default: op
  practice.permission.duel:
    description: "Allows player to use the /duel command."
    default: true
  practice.permission.accept:
    description: "Allows player to use the /accept command."
    default: true
  practice.permission.ext:
    description: "Allows player to use the /ext command."
    default: op
  practice.permission.clear-inv:
    description: "Allows player to use the /clear-inv command."
    default: op
  practice.permission.stats:
    description: "Allows player to use the /stats command."
    default: true
  practice.permission.stats.reset:
    description: "Allows player to use the /stats clear command."
    default: op
  practice.permission.mute:
    description: "Allows player to use the /mute command."
    default: op
  practice.permission.mute.help:
    description: "Allows player to use the /mute help command."
    default: op
  practice.permission.mute.player:
    description: "Allows player to use the /mute player command."
    default: op
  practice.permission.mute.server:
    description: "Allows player to use the /mute server command."
    default: op
  practice.permission.spec:
    description: "Allows player to use the /spec command."
    default: true
  practice.permission.rank:
    description: "Allows player to use the /rank command."
    default: true
  practice.permission.rank.help:
    description: "Allows player to use the /rank help command."
    default: true
  practice.permission.rank.list:
    description: "Allows player to use the /rank list command."
    default: op
  practice.permission.rank.enable:
    description: "Allows player to use the /rank enable command."
    default: op
  practice.permission.rank.disable:
    description: "Allows player to use the /rank disable command."
    default: op
  practice.permission.rank.player:
    description: "Allows player to use the /rank player command."
    default: op
  practice.permission.teleport:
    description: "Allows player to teleport to a different level."
    default: op
  practice.permission.kickall:
    description: "Allows player to kick everyone against."
    default: op
  practice.permission.cleareffects:
    description: "Allows player to clear all effects of all players in the server."
    default: op
  practice.permission.disguise:
    description: "Allows player to use the /disguise command."
    default: true
  practice.permission.disguise.on:
    description: "Allows player to use the /disguise on command."
    default: true
  practice.permission.disguise.off:
    description: "Allows player to use the /disguise off command."
    default: true
  practice.permission.ping:
    description: "Allows player to use the /ping command."
    default: true
  practice.permission.tplevel:
    description: "Allows player to use the /tplevel command."
    default: op
  practice.permission.party.create:
    description: "Allows player to create parties."
    default: op
  practice.permission.pinfo:
    description: "Allows player to see other player's info."
    default: op
  practice.permission.report.clear:
    description: "Allows player to clear all reports."
    default: op